- name: Install prerequisites
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates 
      - curl

- name: Add an Apt signing key
  ansible.builtin.apt_key:
    url: https://baltocdn.com/helm/signing.asc
    state: present

- name: Add specified repository into sources list
  ansible.builtin.apt_repository:
    repo: deb https://baltocdn.com/helm/stable/debian/ all main
    state: present

- name: Install helm
  apt:
    pkg: helm

